services:
  backendlabs_1:
    image: be_lab_1
    build:
      context: .
      dockerfile: BE-lab1/Dockerfile
    ports:
      - "5444:8080"
  backendlabs_2:
    depends_on: 
      - postgresLab_3
    image: be_lab_2
    build:
      context: .
      dockerfile: BE-lab2/Dockerfile
    ports:
      - "5445:8080"
  postgresLab_3:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "Lab3"
    ports:
      - "5437:5432"

