services:
  backendlabs_1:
    image: be_lab_1
    build:
      context: .
      dockerfile: BE-lab1/Dockerfile
    ports:
      - "5444:8080"
  backendlabs_2:
    image: be_lab_2
    build:
      context: .
      dockerfile: BE-lab2/Dockerfile
    ports:
      - "5445:8080"
